// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyzLBBbdTZA5pwH1i36iOvm3Rmkc46YWA',
    appId: '1:586767218576:web:7cb6ac721ab16df6072515',
    messagingSenderId: '586767218576',
    projectId: 'oyeshi-70387',
    authDomain: 'oyeshi-70387.firebaseapp.com',
    storageBucket: 'oyeshi-70387.firebasestorage.app',
    measurementId: 'G-D61G30HEP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyActDWn51Hr1UF8hNgS3eiV4NrC7ESWn-o',
    appId: '1:586767218576:android:d5e41ee9b2d9a177072515',
    messagingSenderId: '586767218576',
    projectId: 'oyeshi-70387',
    storageBucket: 'oyeshi-70387.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJnHWT08bhVwHV5yKII9j3yPVraBZVFCY',
    appId: '1:586767218576:ios:bf6eb1fffa9f16e3072515',
    messagingSenderId: '586767218576',
    projectId: 'oyeshi-70387',
    storageBucket: 'oyeshi-70387.firebasestorage.app',
    iosBundleId: 'com.example.oyeshiDes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJnHWT08bhVwHV5yKII9j3yPVraBZVFCY',
    appId: '1:586767218576:ios:bf6eb1fffa9f16e3072515',
    messagingSenderId: '586767218576',
    projectId: 'oyeshi-70387',
    storageBucket: 'oyeshi-70387.firebasestorage.app',
    iosBundleId: 'com.example.oyeshiDes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyzLBBbdTZA5pwH1i36iOvm3Rmkc46YWA',
    appId: '1:586767218576:web:bd63ef0ece520f37072515',
    messagingSenderId: '586767218576',
    projectId: 'oyeshi-70387',
    authDomain: 'oyeshi-70387.firebaseapp.com',
    storageBucket: 'oyeshi-70387.firebasestorage.app',
    measurementId: 'G-3XNJ8K4Y0W',
  );
}
